services:
  focus_reflex:
    build: .
    container_name: focus_reflex
    restart: always
    # ports:
    #   - "3939:3939"
    volumes:
      - type: bind
        source: $PWD/static
        target: /app/static
    environment:
      - ENV=production
